[[main]]
name = "posts"
title = "Posts"
url = "/posts/"
weight = 1

[[main]]
name = "about"
title = "About"
url = "/about/"
weight = 2

[[main]]
name = "resume"
title = "Resume"
url = "/resume/"
weight = 3

[[main]]
name = "foss"
title = "FOSS"
url = "/foss/"
weight = 4

[[main]]
name = "github"
title = "GitHub"
pre = "github"
url = "https://github.com/sujithh"
weight = 5
